apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping-container
        image: khadar099/shopping:v.1
        ports:
        - containerPort: 8082
