apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30036  # You can choose any port in the range 30000-32767
